teste_nexxas1b/importCSV3/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/import'

	  resources :users do
	  collection { post :import }
  end
  
  root to: "users#index"
  

end

teste_nexxas1b/importCSV3/app/models/user.rb
class User < ActiveRecord::Base
	require 'csv'
		
	# a class method import, with file pass through as an argument
	def self.import(file)
		#file = file.path if file.is_a?(File)
		CSV.foreach(file.path, headers: true) do |row|
			#create a user for each row in the CSV file
			User.create! row.to_hash
		end
	end
end

teste_nexxas1b/importCSV3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

teste_nexxas1b/importCSV3/app/controllers/user_controller.rb
class UserController < ApplicationController
 def index
	@users = User.all
  end

  def self.import
	User.import(params[:file])
	# after the import, redirect and let us know the method worked!
	redirect_to root_url, notice: "Activity Data imported!"
  end
end

teste_nexxas1b/importCSV3/app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
	@users = User.all
  end

  def self.import
	User.import(params[:file])
	# after the import, redirect and let us know the method worked!
	redirect_to root_url, notice: "Activity Data imported!"
  end
end

teste_nexxas1b/importCSV3/app/helpers/application_helper.rb
module ApplicationHelper
end

teste_nexxas1b/importCSV3/app/helpers/users_helper.rb
module UsersHelper
end

teste_nexxas1b/importCSV3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImportCSV3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

teste_nexxas1b/importCSV3/app/views/users/import.html.erb
<h1>Users#import</h1>
<p>Find me in app/views/users/import.html.erb</p>

teste_nexxas1b/importCSV3/app/views/users/index.html.erb
<h1>Users#index</h1>
<%= flash[:notice] %>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Steps</th>
			<th>Distance</th>
			<th>Minutes Exercised</th>
			<th>Hours of Sleep</th>
			<th>Calories Burned</th>
		</tr>
	</thead>
	<tbody>
		<% @users.order("steps desc").each do |user| %>
			<tr>
				<td><%= user.user %></td>
				<td><%= user.steps %></td>
				<td><%= user.distance %></td>
				<td><%= user.exercise %></td>
				<td><%= user.sleep %></td>
				<td><%= user.calories %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<div>

<h4>Import that data!</h4>
	<%= form_tag import_users_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import CSV" %>
	<% end %>
</div>
<p>Find me in app/views/users/index.html.erb</p>